# Writes the corpus's committed packages as a C++ table (EmbeddedPackages.h): every package
# presets/MANIFEST lists, in its order, from the .bsp beside each document, byte for byte.
# Run at build time (GoldenPackages.cmake), so the table follows the committed files.
#   cmake -DPRESETS=dsp/tests/golden/presets -DOUT=GoldenPackages.cpp -P EmbedPackages.cmake
foreach(v PRESETS OUT)
  if(NOT DEFINED ${v})
    message(FATAL_ERROR "EmbedPackages.cmake: ${v} is not set")
  endif()
endforeach()
if(NOT EXISTS "${PRESETS}/MANIFEST")
  message(FATAL_ERROR "EmbedPackages.cmake: ${PRESETS}/MANIFEST is missing")
endif()

# bspc roundtrip --write-manifest's lines: package, sound and control hashes, then the path.
file(STRINGS "${PRESETS}/MANIFEST" lines)
string(REPEAT "0x[0-9a-f][0-9a-f]," 16 byte16)
set(arrays "")
set(table "")
set(index 0)
foreach(line IN LISTS lines)
  if(NOT line MATCHES "^[0-9a-f]+ [0-9a-f]+ [0-9a-f]+ ([A-Za-z0-9_.-]+)[.]json$")
    message(FATAL_ERROR "EmbedPackages.cmake: not a manifest line in ${PRESETS}/MANIFEST: '${line}'")
  endif()
  set(name "${CMAKE_MATCH_1}")
  set(bsp "${PRESETS}/${name}.bsp")
  if(NOT EXISTS "${bsp}")
    message(FATAL_ERROR "EmbedPackages.cmake: ${bsp}, which MANIFEST lists, is missing")
  endif()
  file(SIZE "${bsp}" size)
  file(READ "${bsp}" hex HEX)
  string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," hex "${hex}")
  string(REGEX REPLACE "(${byte16})" "    \\1\n" hex "${hex}")  # 16 bytes a line
  string(APPEND arrays "// ${name}.bsp, ${size} bytes\nalignas(8) const uint8_t kPackage${index}[] = {\n${hex}\n};\n")
  string(APPEND table "    {\"${name}\", kPackage${index}, ${size}u},\n")
  math(EXPR index "${index} + 1")
endforeach()
if(index EQUAL 0)
  message(FATAL_ERROR "EmbedPackages.cmake: ${PRESETS}/MANIFEST lists no package")
endif()

set(text "// Generated by dsp/tests/golden/EmbedPackages.cmake from presets/MANIFEST and the .bsp
// files beside it. Do not edit.
#include <cstddef>
#include <cstdint>

#include \"EmbeddedPackages.h\"

namespace brainscape::golden {

namespace {

${arrays}
const EmbeddedPackage kPackages[] = {
${table}};

}  // namespace

const EmbeddedPackage* EmbeddedPackages(size_t* count) noexcept {
  *count = sizeof kPackages / sizeof kPackages[0];
  return kPackages;
}

}  // namespace brainscape::golden
")
if(EXISTS "${OUT}")
  file(READ "${OUT}" old)
  if(old STREQUAL text)
    return()
  endif()
endif()
file(WRITE "${OUT}" "${text}")
