# Writes the SHA-256 of the engine archives the firmware links into a header, so every image
# can report it (its hello line): the shipping archive must be byte-identical to the one the
# parity-m7 CI job audits and renders the golden corpus with under qemu-arm.
# OUT_LIST gets the same hashes in sha256sum's format, for the host tools' --expect-archive.
#   cmake -DARCHIVE=libbrainscape_dsp.a -DHOOKS_ARCHIVE=... -DOUT=header -DOUT_LIST=file
#         -P ArchiveSha256.cmake
file(SHA256 "${ARCHIVE}" sha)
file(SHA256 "${HOOKS_ARCHIVE}" hooks)
if(OUT_LIST)
  file(WRITE "${OUT_LIST}" "${sha}  libbrainscape_dsp.a\n${hooks}  libbrainscape_dsp_fpenv_hooks.a\n")
endif()
set(text "// Generated by firmware/cmake/ArchiveSha256.cmake. Do not edit.\n#pragma once\n#define BRAINSCAPE_ENGINE_ARCHIVE_SHA256 \"${sha}\"\n#define BRAINSCAPE_HOOKS_ARCHIVE_SHA256 \"${hooks}\"\n")
if(EXISTS "${OUT}")
  file(READ "${OUT}" old)
  if(old STREQUAL text)
    return()
  endif()
endif()
file(WRITE "${OUT}" "${text}")
