# Writes the source tree's commit and whether it has uncommitted changes into a header, at
# every build (the hello line reports them), rewriting it only when they change.
#   cmake -DSOURCE_DIR=... -DOUT=... [-DGIT=git] -P GitInfo.cmake
set(commit "unknown")
set(dirty "false")
if(GIT)
  execute_process(COMMAND "${GIT}" rev-parse --short=12 HEAD WORKING_DIRECTORY "${SOURCE_DIR}"
                  OUTPUT_VARIABLE out OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET RESULT_VARIABLE rc)
  if(rc EQUAL 0)
    set(commit "${out}")
    execute_process(COMMAND "${GIT}" status --porcelain --untracked-files=no
                    WORKING_DIRECTORY "${SOURCE_DIR}" OUTPUT_VARIABLE changes ERROR_QUIET)
    if(NOT changes STREQUAL "")
      set(dirty "true")
    endif()
  endif()
endif()
set(text "// Generated by firmware/cmake/GitInfo.cmake. Do not edit.\n#pragma once\n#define BRAINSCAPE_GIT_COMMIT \"${commit}\"\n#define BRAINSCAPE_GIT_DIRTY ${dirty}\n")
if(EXISTS "${OUT}")
  file(READ "${OUT}" old)
  if(old STREQUAL text)
    return()
  endif()
endif()
file(WRITE "${OUT}" "${text}")
